 <?php
/**
* HungnamEcommerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://hungnamecommerce.com/HN-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   HN
 * @package    HN_PIN
 * @version    2.0.2
 * @copyright  Copyright (c) 2012-2013 HungnamEcommerce Co. (http://hungnamecommerce.com)
 * @license    http://hungnamecommerce.com/HN-LICENSE-COMMUNITY.txt
 */

?>
<?php
/**
 * Template for Mage_Adminhtml_Block_Catalog_Product_Edit
 */
?>
<style>
/*
 * FancyBox - jQuery Plugin
 * Simple and fancy lightbox alternative
 *
 * Examples and documentation at: http://fancybox.net
 * 
 * Copyright (c) 2008 - 2010 Janis Skarnelis
 * That said, it is hardly a one-person project. Many people have submitted bugs, code, and offered their advice freely. Their support is greatly appreciated.
 * 
 * Version: 1.3.4 (11/11/2010)
 * Requires: jQuery v1.3+
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */

#fancybox-loading {
	position: fixed;
	top: 50%;
	left: 50%;
	width: 40px;
	height: 40px;
	margin-top: -20px;
	margin-left: -20px;
	cursor: pointer;
	overflow: hidden;
	z-index: 1104;
	display: none;
}

#fancybox-loading div {
	position: absolute;
	top: 0;
	left: 0;
	width: 40px;
	height: 480px;
	background-image: url('fancybox.png');
}

#fancybox-overlay {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	z-index: 1100;
	display: none;
}

#fancybox-tmp {
	padding: 0;
	margin: 0;
	border: 0;
	overflow: auto;
	display: none;
}

#fancybox-wrap {
	position: absolute;
	top: 0;
	left: 0;
	padding: 20px;
	z-index: 1101;
	outline: none;
	display: none;
}

#fancybox-outer {
	position: relative;
	width: 100%;
	height: 100%;
	background: #fff;
}

#fancybox-content {
	width: 0;
	height: 0;
	padding: 0;
	outline: none;
	position: relative;
	overflow: hidden;
	z-index: 1102;
	border: 0px solid #fff;
}

#fancybox-hide-sel-frame {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background: transparent;
	z-index: 1101;
}

#fancybox-close {
	position: absolute;
	top: -15px;
	right: -15px;
	width: 30px;
	height: 30px;
	background: transparent url('fancybox.png') -40px 0px;
	cursor: pointer;
	z-index: 1103;
	display: none;
}

#fancybox-error {
	color: #444;
	font: normal 12px/20px Arial;
	padding: 14px;
	margin: 0;
}

#fancybox-img {
	width: 100%;
	height: 100%;
	padding: 0;
	margin: 0;
	border: none;
	outline: none;
	line-height: 0;
	vertical-align: top;
}

#fancybox-frame {
	width: 100%;
	height: 100%;
	border: none;
	display: block;
}

#fancybox-left, #fancybox-right {
	position: absolute;
	bottom: 0px;
	height: 100%;
	width: 35%;
	cursor: pointer;
	outline: none;
	background: transparent url('blank.gif');
	z-index: 1102;
	display: none;
}

#fancybox-left {
	left: 0px;
}

#fancybox-right {
	right: 0px;
}

#fancybox-left-ico, #fancybox-right-ico {
	position: absolute;
	top: 50%;
	left: -9999px;
	width: 30px;
	height: 30px;
	margin-top: -15px;
	cursor: pointer;
	z-index: 1102;
	display: block;
}

#fancybox-left-ico {
	background-image: url('fancybox.png');
	background-position: -40px -30px;
}

#fancybox-right-ico {
	background-image: url('fancybox.png');
	background-position: -40px -60px;
}

#fancybox-left:hover, #fancybox-right:hover {
	visibility: visible; /* IE6 */
}

#fancybox-left:hover span {
	left: 20px;
}

#fancybox-right:hover span {
	left: auto;
	right: 20px;
}

.fancybox-bg {
	position: absolute;
	padding: 0;
	margin: 0;
	border: 0;
	width: 20px;
	height: 20px;
	z-index: 1001;
}

#fancybox-bg-n {
	top: -20px;
	left: 0;
	width: 100%;
	background-image: url('fancybox-x.png');
}

#fancybox-bg-ne {
	top: -20px;
	right: -20px;
	background-image: url('fancybox.png');
	background-position: -40px -162px;
}

#fancybox-bg-e {
	top: 0;
	right: -20px;
	height: 100%;
	background-image: url('fancybox-y.png');
	background-position: -20px 0px;
}

#fancybox-bg-se {
	bottom: -20px;
	right: -20px;
	background-image: url('fancybox.png');
	background-position: -40px -182px; 
}

#fancybox-bg-s {
	bottom: -20px;
	left: 0;
	width: 100%;
	background-image: url('fancybox-x.png');
	background-position: 0px -20px;
}

#fancybox-bg-sw {
	bottom: -20px;
	left: -20px;
	background-image: url('fancybox.png');
	background-position: -40px -142px;
}

#fancybox-bg-w {
	top: 0;
	left: -20px;
	height: 100%;
	background-image: url('fancybox-y.png');
}

#fancybox-bg-nw {
	top: -20px;
	left: -20px;
	background-image: url('fancybox.png');
	background-position: -40px -122px;
}

#fancybox-title {
	font-family: Helvetica;
	font-size: 12px;
	z-index: 1102;
}

.fancybox-title-inside {
	padding-bottom: 10px;
	text-align: center;
	color: #333;
	background: #fff;
	position: relative;
}

.fancybox-title-outside {
	padding-top: 10px;
	color: #fff;
}

.fancybox-title-over {
	position: absolute;
	bottom: 0;
	left: 0;
	color: #FFF;
	text-align: left;
}

#fancybox-title-over {
	padding: 10px;
	background-image: url('fancy_title_over.png');
	display: block;
}

.fancybox-title-float {
	position: absolute;
	left: 0;
	bottom: -20px;
	height: 32px;
}

.search_list li:hover{
    cursor: pointer;
}

.search_list {
    z-index: 999;
    background-color: #ffffff;
}

#fancybox-title-float-wrap {
	border: none;
	border-collapse: collapse;
	width: auto;
}

#fancybox-title-float-wrap td {
	border: none;
	white-space: nowrap;
}

#fancybox-title-float-left {
	padding: 0 0 0 15px;
	background: url('fancybox.png') -40px -90px no-repeat;
}

#fancybox-title-float-main {
	color: #FFF;
	line-height: 29px;
	font-weight: bold;
	padding: 0 0 3px 0;
	background: url('fancybox-x.png') 0px -40px;
}

#fancybox-title-float-right {
	padding: 0 0 0 15px;
	background: url('fancybox.png') -55px -90px no-repeat;
}

/* IE6 */

.fancybox-ie6 #fancybox-close { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_close.png', sizingMethod='scale'); }

.fancybox-ie6 #fancybox-left-ico { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_nav_left.png', sizingMethod='scale'); }
.fancybox-ie6 #fancybox-right-ico { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_nav_right.png', sizingMethod='scale'); }

.fancybox-ie6 #fancybox-title-over { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_title_over.png', sizingMethod='scale'); zoom: 1; }
.fancybox-ie6 #fancybox-title-float-left { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_title_left.png', sizingMethod='scale'); }
.fancybox-ie6 #fancybox-title-float-main { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_title_main.png', sizingMethod='scale'); }
.fancybox-ie6 #fancybox-title-float-right { background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_title_right.png', sizingMethod='scale'); }

.fancybox-ie6 #fancybox-bg-w, .fancybox-ie6 #fancybox-bg-e, .fancybox-ie6 #fancybox-left, .fancybox-ie6 #fancybox-right, #fancybox-hide-sel-frame {
	height: expression(this.parentNode.clientHeight + "px");
}

#fancybox-loading.fancybox-ie6 {
	position: absolute; margin-top: 0;
	top: expression( (-20 + (document.documentElement.clientHeight ? document.documentElement.clientHeight/2 : document.body.clientHeight/2 ) + ( ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop )) + 'px');
}

#fancybox-loading.fancybox-ie6 div	{ background: transparent; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_loading.png', sizingMethod='scale'); }

/* IE6, IE7, IE8 */

.fancybox-ie .fancybox-bg { background: transparent !important; }

.fancybox-ie #fancybox-bg-n { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_n.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-ne { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_ne.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-e { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_e.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-se { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_se.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-s { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_s.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-sw { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_sw.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-w { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_w.png', sizingMethod='scale'); }
.fancybox-ie #fancybox-bg-nw { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='fancybox/fancy_shadow_nw.png', sizingMethod='scale'); }
</style>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/jquery-1.5.1.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/jquery.fancybox-1.3.4.pack.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/noc.js') ?>"></script>
 <script type="text/javascript">
jQuery(document).ready(function() {
    var timer;
    var ajaxUrl = "<?php echo $this->getUrl('pin/adminhtml_pin/searchAjaxCWProducts').'?ajax=true&isAjax=true'?>";
    var formKey = "<?php echo $this->getFormKey()?>";

	jQuery("#fancyimg").fancybox();

	jQuery("#fancyzip").fancybox();

    closeDiv = function(el){
        jQuery(jQuery(el).parent()).parent().hide();
    }

    hideDiv = function(el){
        var id = jQuery(el).data("id");
        jQuery("#cw_product_id").val(id);
        var name = jQuery(el).children().text();
        jQuery("#corr_search").val(name);
        closeDiv(el);
    }

    //TODO clear the value of corresponding product

    showDiv = function(products){
        var el = jQuery("#corr_search");
        var str = "<ul class='search_list'>";
        if(products.length > 0){
            jQuery.each(products, function(key,product){
                str = str+"<li data-id='"+product.id+"' onclick='hideDiv(this)'><b>"+product.name+"</b></li>";
            });
        }else{
            str = str + "<li>No results<li>";
        }
        str = str + "<li onclick='closeDiv(this)'><a><span>close</span></a><li>";
        str = str+"</ul>";
        if(jQuery(".search_products_div").length > 0){
            jQuery(".search_products_div").html(str).css('display','inline-block');
        }else{
            var div = jQuery('<div class="search_products_div" />').html(str)
                .css('display', 'inline-block')
                .css('position', 'absolute')
                .css('top', el.outerHeight() + el.offset().top)
                .css('left', el.position().left)
                .css('min-width', '200px')
                .css('min-height', '20px')
                .css('border', '1px solid #000');
            el.after(div);
        }
    }

    showPopup = function(el){
        var val = jQuery(el).val();
        if(val){
            data = {
                form_key: formKey,
                value: val
            };
            jQuery.ajax({
                url: ajaxUrl,
                type: "POST",
                data: data,
                success: function(resp){
                    products = JSON.parse(resp);
                    showDiv(products);
                    console.log(products);
                }
            });
        }
    }

    jQuery("#corr_search").keyup(function(){
        clearTimeout(timer);
        var that = this;
        timer = setTimeout(function () {
            showPopup(that);
        }, 600);
    });
}) ;
 </script>
 <?php $_product = $this->getProductInstance()?>
 <div class="entry-edit" >

     <div class="entry-edit-head">
         <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Corresponding product options')?></h4>
     </div>
     <div class="box">
        <form action="<?php echo $this->getUrl('*/kontenta_codeswholesale_index/submit')?>" method="POST">
            <div style="margin-bottom: 20px;">
                <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
                <input type="hidden" name="productid" value="<?php echo $this->getRequest()->getParam('id') ?>" />

                <input type="text" name="corresponding_product" value="" id="corr_search" style="width:150px"/>
                <div>
                    <table class="form-list" cellspacing="0">
                        <tbody>
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__("Sync <b>price</b> with codeswholesale.com") ?></label>
                                </td>
                                <td class="value">
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_sync_price') ? 'checked' : ''?> name="product[kontenta_cw_sync_price]" value="1"><label><?php echo $this->__("Yes")?></label>
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_sync_price') ? '' : 'checked'?> name="product[kontenta_cw_sync_price]" value="0"><label><?php echo $this->__("No")?></label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__("Sync <b>stock</b> with codeswholesale.com") ?></label>
                                </td>
                                <td class="value">
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_sync_stock') ? 'checked' : ''?> name="product[kontenta_cw_sync_stock]" value="1"><label><?php echo $this->__("Yes")?></label>
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_sync_stock') ? '' : 'checked'?> name="product[kontenta_cw_sync_stock]" value="0"><label><?php echo $this->__("No")?></label>
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__("If preorder product; pre order from codeswholesale.com?") ?></label>
                                </td>
                                <td class="value">
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_preorder') ? 'checked' : ''?> name="product[kontenta_cw_preorder]" value="1"><label><?php echo $this->__("Yes")?></label>
                                    <input type="radio" <?php echo $_product->getData('kontenta_cw_preorder') ? '' : 'checked'?> name="product[kontenta_cw_preorder]" value="0"><label><?php echo $this->__("No")?></label>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <input type="hidden" name="product[kontenta_corresponding_product]" value="<?php echo $_product->getKontentaCorrespondingProduct() ? $_product->getKontentaCorrespondingProduct() : ''?>" id="cw_product_id"/>
            </div>
            <div class="buttons-set">
                <button class="button" type="submit"><span><?php echo $this->__("Apply")?></span></button>
            </div>
        </form>
         <?php if($_product->getKontentaCorrespondingProduct()):?>
             <div>
                 <span><?php echo $this->__("Corresponding Product")?></span>
                 -
                 <?php echo Mage::helper("apiplugin")->getProductById($_product->getKontentaCorrespondingProduct())->getName()?>
             </div>
         <?php endif;?>
     </div>
 </div>
 <div class="entry-edit" >
                       <div class="entry-edit-head">
                       			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Game license delivery')?></h4>
                       </div>
                       
 </div>
                   


<div id="pincontainer"></div>
	
	

	<?php 
	$productId = $this->getProductId();
	if ($productId && $productId > 0) {

	?>
	<a  id="fancyimg" href="<?php echo Mage::getBaseUrl() ?>/pin/adminhtml_pin/product?productid=<?php echo  $productId ?>" ><?php echo $this->__('Add PIN') ?></a>
	
	<div>
	      	<a  id="fancyzip" href="<?php echo Mage::getBaseUrl() ?>/pin/adminhtml_pin/uploadzip?productid=<?php echo  $productId ?>" ><?php echo $this->__('Add PIN using zip file') ?></a>
	      
	</div>
	
	<?php  } else { ?>
	<span class="pin_empty_product"> <?php echo $this->__('Please save product first then edit product to add PIN') ?> </span>
	<?php } ?>
	
	<?php echo  Mage::app()->getLayout()->createBlock('pin/adminhtml_catalog_product_grid')->toHtml()?>