<?php
$checked = null;
 if ( Mage::helper('pin')->isPinProduct($_GET['productid']) && $_GET['productid'] != 0)  
 {
 	$checked = true;
 }
 
 $isPinProduct = Mage::getModel('pin/ispinproduct')->load($_GET['productid'], 'product_id');
?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/jquery-1.5.1.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/noc.js') ?>"></script>
<form method="POST" action="<?php echo $this->getUrl('pin/adminhtml_pin/saveimage') ?>" enctype="multipart/form-data" id="product_pin">
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />  
<input type="hidden" name="productid" value="<?php echo $_GET['productid'] ?>" />  

<table id="image_pin_tbl">
<tr>
<td>
<input type="checkbox" name="ispinproduct" <?php if ($checked) { ?> checked  <?php } ?> />
</td>
<td><?php echo $this->__('Is PIN product') ?></td>
</tr>

    <tr>
        <td><?php echo $this->__("Invoice ID") ?></td>
        <td><input type="text" name="pin_invoice_id"/></td>
    </tr>

<tr>
<td><?php echo $this->__('PIN type') ?></td>
<td>
<select name="pin_type" onchange="{
var optionVal = this.value;
if (optionVal  == 1) {
	var filesE = document.getElementsByClassName('file_input');
	 for (var i = 0; i < filesE.length; i++) {
		filesE[i].setAttribute('style', 'display:none');
     }
     
     var textE = document.getElementsByClassName('text_input');
	 for (var i = 0; i < textE.length; i++) {
		textE[i].setAttribute('style', 'display:');
     }
    
} 
if (optionVal  == 2) {
    var filesE = document.getElementsByClassName('text_input');
	 for (var i = 0; i < filesE.length; i++) {
		filesE[i].setAttribute('style', 'display:none');
     }
     
     var textE = document.getElementsByClassName('file_input');
	 for (var i = 0; i < textE.length; i++) {
		textE[i].setAttribute('style', 'display:');
     }
   
} 
}
">
<option value="0"><?php echo $this->__('Please select')?> </option>
<option value="1" <?php if ($isPinProduct->getType() == 1) { ?> selected="selected" <?php } ?> ><?php echo $this->__('text') ?></option>
<option value="2" <?php if ($isPinProduct->getType() == 2) { ?> selected="selected" <?php } ?> > <?php echo $this->__('file') ?></option>

</select>
</td>
</tr>
<tr class="file_input"  <?php if ($isPinProduct->getType() == 1) { ?> style="display:none" <?php } ?> >
<td><?php echo $this->__('PIN') ?></td><td><input name="img[]" type="file" /></td> 

<td><button onclick='{

    var table = document.getElementById("image_pin_tbl");

    var rowCount = table.rows.length;
    var row = table.insertRow(rowCount);
    row.setAttribute("class" , "file_input");
    var cell1 = row.insertCell(0);
    
    cell1.innerHTML = "PIN :";

    

    var cell3 = row.insertCell(1);
    var element2 = document.createElement("input");
    element2.type = "file";
     element2.name = "img[]";
    cell3.appendChild(element2);
    return false;
}'><?php echo $this->__('Add more') ?></button></td></tr>

<tr class="text_input" <?php if ($isPinProduct->getType() == 2) { ?> style="display:none" <?php } ?> >
<td><?php echo $this->__('PIN') ?></td><td><input name="pin[]" type="text" /></td> 
<td><button onclick='{

    var table = document.getElementById("image_pin_tbl");

    var rowCount = table.rows.length;
    var row = table.insertRow(rowCount);
    row.setAttribute("class" , "text_input");
   
    var cell1 = row.insertCell(0);
    
    cell1.innerHTML = "PIN :";

    

    var cell3 = row.insertCell(1);
    var element2 = document.createElement("input");
    element2.type = "text";
    element2.name = "pin[]";
    cell3.appendChild(element2);
    return false;
}'><?php echo $this->__('Add more') ?></button></td></tr>
</table>
<input type="submit" value="<?php echo $this->__('Upload') ?>" />

<input type="hidden" value="0" style="display:none" id="countpinimg" />
</form>


 