<?php
$checked = null;
 if ( Mage::helper('pin')->isPinProduct($_GET['productid']) && $_GET['productid'] != 0)  
 {
 	$checked = true;
 }
?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/jquery-1.5.1.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('fancybox/noc.js') ?>"></script>
 <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload zip file') ?></h2>
        
        <span><?php echo $this->__('The PIN (bar code images ) must be uploaded in a zip file. This zip file can contain one or more barcode') ?></span>
        <span><?php echo $this->__('If you upload zip file then the pin type is file not encrypted text') ?></span>
       
<!--  -->
<form method="POST" action="<?php echo $this->getUrl('pin/adminhtml_pin/savezip') ?>" enctype="multipart/form-data" id="product_pin">
<input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />  
<input type="hidden" name="productid" value="<? echo $_GET['productid'] ?>" />  

<table id="image_pin_tbl">
<tr>
<td>
<input type="checkbox" name="ispinproduct" <?php if ($checked) { ?> checked  <?php } ?> />
</td>
<td><?php echo $this->__('Is PIN product') ?></td>
</tr>

<tr class="file_input" >
<td><?php echo $this->__('Zip file') ?></td><td><input name="imgzip" type="file" /></td> 

</tr>

</table>
<input type="submit" value="<?php echo $this->__('Upload') ?>" />

<input type="hidden" value="0" style="display:none" id="countpinimg" />
</form>

</div>
 