<?php $_products = $this->getCwProducts()?>
<?php $_productsMagento = $this->getAllProducts()?>
<h3><?php echo $this->__("List all products from Codeswholesale.com that are not synced with Magento")?></h3>
<ol type="1">
<?php foreach($_products as $product):?>
    <li><span <?php echo !in_array($product->getProductId(), $_productsMagento) ? "style=' text-decoration: underline;font-weight:bold'" : "" ?> ><?php echo $product->getName()?></span></li>
<?php endforeach;?>
</ol>